### ISSUE TITLE
Linux-ish

### ISSUE THREAD

**Issue by gates19** [android/media-samples#15]
is it possible to launch pip activity directly from a terminal using am command;
i.e., am start -n pkg.name/pkg.activity

**Comment by ffffaaasl** [comment]
> is it possible to launch pip activity directly from a terminal using am command;
> 
> i.e., am start -n pkg.name/pkg.activity

**Comment by nic0lette** [comment]
You might be able to use:

`am start -n pkg.name/pkg.activity --windowingMode 2` where `2` maps to `WINDOWING_MODE_PINNED` in [WindowConfiguration](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/WindowConfiguration.java;l=83-91)
