### ISSUE TITLE
ExoPlayer in RecyclerView

### ISSUE THREAD

**Issue by CelikAbdullah** [android/media-samples#58]
Hello, 

I wanted to ask if you can also provide a sample with a combination of ExoPlayer and RecyclerView.
So, having a RecyclerView with some Video items and ExoPlayer showing those items while scrolling through the list. 

I tried it but releasing the ExoPlayer after one video is handled is a great problem. It did not work very well for me.

**Comment by nic0lette** [comment]
There's an issue on the ExoPlayer project's issue tracker for this, so I'd suggest following that issue (and reading the replies to see if any of them help your particular use case): [How to use ExoPlayer in a ListvVew or RecyclerView?](https://github.com/google/ExoPlayer/issues/867)
